.gitignore
.rspec
Appraisals
Gemfile
LICENSE.txt
Makefile
README.md
Rakefile
bin/console
lib/string_tools.rb
lib/string_tools/core_ext/string.rb
lib/string_tools/version.rb
spec/spec_helper.rb
spec/string_tools_spec.rb
string_tools.gemspec

Code merged from Apress::Utils and Plugin base_class_extensions/string
Closes [SG-3689](https://jira.railsc.ru/browse/SG-3689)

feat: Initial commit

---

lib/string_tools/core_ext/string.rb

https://jira.railsc.ru/browse/BPC-6652

feature(BPC-6652): removing open comment tags

---

lib/string_tools/html.rb

https://jira.railsc.ru/browse/SERVICES-594
https://github.com/abak-press/apress-products/pull/66#discussion_r41950430

chore: костанта с минимальным размером строки содержащей ссылки

---

lib/string_tools/html.rb
spec/html_spec.rb

https://jira.railsc.ru/browse/SERVICES-594

fix(html): поддержка относительных путей

---

lib/string_tools/html.rb
spec/html_spec.rb

https://jira.railsc.ru/browse/SERVICES-594

feature(html): удаление ссылок без хоста по-умолчанию

---

lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/CK-30

feature: перенос методов очистки от html-разметки

---

lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/PC4-15878

feature(string_tools): add params concatenation method

---

.gitignore
lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/PC4-16353

fix(lib/string_tools) add default_url in add_params_to_url

---

Makefile
lib/string_tools.rb
lib/string_tools/html.rb
spec/html_spec.rb
spec/string_tools_spec.rb
string_tools.gemspec

https://jira.railsc.ru/browse/SERVICES-906

fix(sanitizers): подменять невалидные ссылки своим содержимым

---

lib/string_tools.rb
spec/fixtures/lsps.txt
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/SERVICES-1040

feat: add clearing deprecated unicode characters

---

.drone.yml
Gemfile
dip.yml
docker-compose.development.yml
docker-compose.drone.yml
docker-compose.yml
lib/string_tools/core_ext/string.rb
spec/string_spec.rb
string_tools.gemspec

https://jira.railsc.ru/browse/CK-497

feature: add String#mb_downcase method

---

lib/string_tools.rb
spec/string_tools_spec.rb

Closes https://github.com/abak-press/string_tools/issues/23

fix: check String class from std lib

---

lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/GOODS-638

feature: iframe normalizer

---

lib/string_tools.rb
lib/string_tools/version.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/CK-1371

fix: не мутировать дефолтный конфиг при многократном вызове sanitize

---

lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/GOODS-1146
:link: https://github.com/abak-press/apress-text_editor/pull/72

feat: adds s tag as allowed

---

lib/string_tools.rb
lib/string_tools/version.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/GOODS-1246

fix: use correct tag for js

---

lib/string_tools/core_ext/string.rb
spec/string_spec.rb

https://jira.railsc.ru/browse/GOODS-1126

feature: removing nonprintable characters

---

Appraisals
lib/string_tools/core_ext/string.rb
spec/string_spec.rb

https://jira.railsc.ru/browse/GOODS-2001

chore: test rails 4.0 - 4.2

---

lib/string_tools.rb
spec/string_tools_spec.rb
string_tools.gemspec

https://jira.railsc.ru/browse/GOODS-2219
В goods-april1

feature: optionally turn off uri normalization

---

.drone.yml
Appraisals
Gemfile
Rakefile
bin/console
dip.yml
lib/string_tools.rb
lib/string_tools/core_ext/string.rb
lib/string_tools/html.rb
lib/string_tools/string.rb
lib/string_tools/version.rb
spec/html_spec.rb
spec/spec_helper.rb
spec/string_spec.rb
spec/string_tools/string_spec.rb
spec/string_tools_spec.rb
string_tools.gemspec

https://jira.railsc.ru/browse/BPC-19154

feature: add support for ruby v2.4

---

lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/PC4-29908

feat: add options for sanitize outer links in css

---

lib/string_tools.rb
lib/string_tools/version.rb
spec/string_tools_spec.rb

You don't need to do anything on connection

MERGE: pc-ck-editor-blocks into master and Release 1.1.0

---

lib/string_tools/core_ext/string.rb

https://jira.railsc.ru/browse/SG-8626

 feature(string): change String#strip_tags 

---

lib/string_tools.rb
spec/string_tools_spec.rb

https://jira.railsc.ru/browse/PC4-31420
**Нужна ветка: pc-rutube-hosting**

feat(ck-editor video hosting): add rutube

---

lib/string_tools.rb
lib/string_tools/version.rb
spec/string_tools_spec.rb

[#33600](https://github.com/abak-press/pulscen/pull/33600)
@bayerd412
Дополнительных действий не требуется.
Задача согласована с Близко:
https://jira.railsc.ru/browse/PC4-31390

Merge pc-rutube into master and Release 1.3.0
